server:
    port: 8080

spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties.hibernate.hbm2ddl.auto: update
        showSql: true
    messages:
        basename: i18n/exception
        encoding: UTF-8
    jwt:
        secret:eastperson123#@!